export { default as AFR } from "./AFR.vue"
export { default as AFRProfile } from "./AFRProfile.vue"
export { default as AFRTitle } from "./AFRTitle.vue"
export { default as AFRTable } from "./AFRTable.vue"
export { default as AFRRow } from "./AFRRow.vue"
export { default as AFRGPA } from "./AFRGPA.vue"
export { default as AFRDisclaimer } from "./AFRDisclaimer.vue"